services:
  - type: web
    name: womens-march-madness
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: TWITTER_BEARER_TOKEN
        sync: false
      - key: ODDS_API_KEY
        sync: false
    autoDeploy: true 